### ISSUE TITLE
Setting contrast and brightness of individual ROIs

### ISSUE THREAD

**Issue by Amatzia** [guatek/Dual-Mag-Data#1]
Would be nice to have the brightness and contrast controls for individual ROIs (similar to those controls in viewing full images).
Amatzia

**Comment by guatek** [comment]
This is a great suggestion. I'll add this to the next commit.

**Comment by guatek** [comment]
This feature was added in commit https://github.com/guatek/Dual-Mag-Data/commit/2301cb03c9d7f6c7aecc29e98d9ad4c5656f0acf 

To use this feature you can download the repo again and then you have two options:

1. Copy the contents of the webapp directory from the downloaded repo over an existing webapp directory output from proc_directory.py and reopen index.html (must faster as it just updates the UI)
2. Reprocess the data using the updated code (much slower)
